apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    project: n8n-demo
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.database.secretName }}
        objectType: secretsmanager
      - objectName: {{ .Values.encryption.secretName }}
        objectType: secretsmanager