apiVersion: v1
kind: Service
metadata:
  name: n8n-webhook
  namespace: n8n
  labels:
    app: n8n
    component: webhook
    project: n8n-demo
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: n8n
    component: webhook