apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-sa
  namespace: n8n
  labels:
    app: n8n
    project: n8n-demo
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}